### ISSUE TITLE
Extractor creates an empty epub

### ISSUE THREAD

**Issue by skafhz** [GMMan/Extractor.epub#1]
When I run the extractor, it creates an empty epub, with title Extrator.epub and saying
"Extracts content from VitalSource EPUBBooks in conjunction with Extractor.epub Backend".

The folder created named after the VBID has the expected structure, but it corresponds with an empty epub. For example, table-of-contents.xhtml has only an item called Extractor.epub.

Although I entered the correct VBID, it does the same if I enter a non-existing VBID. The result is the same.

**Comment by GMMan** [comment]
It sounds like the backend is creating a copy of Extractor.epub itself. In the case of an invalid VBID, you should be getting an error message on the frontend that the book cannot be found, and nothing would happen on the backend. What are you typing in for the file name?

**Comment by skafhz** [comment]
I am typing 9781458712450.vbk for the file name, which is the file for the ebook under C:\Users\Public\Documents\Shared Books\VitalSource Bookshelf\VitalBook Library. I also tried typing 9781458712450.

I am using Windows 7. I also needed to change EPUB Browser Option to WebKit because IE9 or later would say it did not find valid EPUB.

I just downloaded the latest Extractor.epub you published, and now it says "done" when using Webkit, but doesn't save the file or give me the option to download it. It doesn't contact the backend. If using IE9 or later, it says did not find valid EPUB.

Are you using Windows 8?

**Comment by GMMan** [comment]
> I also needed to change EPUB Browser Option to WebKit because IE9 or later would say it did not find valid EPUB.

Indeed, it may not be a valid EPUB, or for that matter, a valid book at all. I couldn't get the book's info from the inventory service either. Are you sure you've got the correct name? The name has to be identical to the file name on disk.

**Comment by skafhz** [comment]
Sorry, this is the correct name: 9781498712460.vbk
It is identical to what I have in my folder.

I am upgrading to Windows 8.1 to test on it also.

**Comment by GMMan** [comment]
The book is in VitalBook format, not EPUB. Extractor.epub only supports EPUBBook format VBKs.
