### ISSUE TITLE
Extractor.epub is no longer working on Bookshelf 6.2

### ISSUE THREAD

**Issue by lextorre** [GMMan/Extractor.epub#10]
I think there was a change in the server configuration recently. New books purchased from august until now cannot be downloaded. Please, could you confirm this?

Thanks in advance.

**Comment by GMMan** [comment]
I don't use Bookshelf Desktop anymore, so I don't know what they might have changed. You'll have better luck if you poke around their Jigsaw-based online reader.

**Comment by lextorre** [comment]
Ok. Thanks again for your attention.
