### ISSUE TITLE
''Did not find valid EPUB with that name. ''

### ISSUE THREAD

**Issue by acnefree** [GMMan/Extractor.epub#11]
it does not work.  these book are in format epubbook.
![1](https://cloud.githubusercontent.com/assets/22470800/18985483/a9104698-872a-11e6-9cdc-84467a16c239.JPG)
![2](https://cloud.githubusercontent.com/assets/22470800/18985481/a90b20c8-872a-11e6-8362-8cec4d9f7352.JPG)
![3](https://cloud.githubusercontent.com/assets/22470800/18985480/a90763ca-872a-11e6-95f6-06b400fd56a6.JPG)
![4](https://cloud.githubusercontent.com/assets/22470800/18985482/a90fc86c-872a-11e6-8803-51158bbb850c.JPG)

9781942471189.vbk  ---   2016 CFA Level I Volume 1 Ethical and Professional Standards and Quantitative Methods
9781942471196.vbk   ---   2016 CFA Level I Volume 2 Economics
9781942471202.vbk     ----    2016 CFA Level I Volume 3 Financial Reporting and Analysis
9781942471219.vbk    ----    2016 CFA Level I Volume 4 Corporate Finance and Portfolio Management
9781942471226.vbk    ----    2016 CFA Level I Volume 5 Equity and Fixed Income
9781942471233.vbk    ----    2016 CFA Level I Volume 6 Derivatives and Alternative Investments

**Comment by acnefree** [comment]
my email address is 
1976793972@qq.com
email me and i'll tell you my Bookshelf Account and passcode. 
RRRRRealy need help, &   DDDDesperately want these books in epub format.

**Comment by GMMan** [comment]
If you're trying to use it on any version of Bookshelf at or beyond version 6.7.0 (16), it's not going to work.
