### ISSUE TITLE
File not found: Unable to open specified file.

### ISSUE THREAD

**Issue by eckucukoglu** [GMMan/Extractor.epub#13]
Hi,

I really not sure that I'm doing it right, however I have to ask;
To sideload 'Extractor.epub', I dragged and dropped book/ directory of these repository. Then try to double click to open then these errors occurred.

I'm not sure that 'Extractor.epub' is that I moved? Moreover, I couldn't get where should I enter the name as written in readme;
- Enter the name into the 'File name' box on Extractor.epub. Then click 'Extract'.

Thanks. :)

**Comment by GMMan** [comment]
The files to download are on the Releases page. Did you follow the instructions at https://support.vitalsource.com/hc/en-us/articles/203256896-Side-load-EPUB-files-to-Bookshelf-for-Mac-PC?

**Comment by eckucukoglu** [comment]
Yes, I followed and add the Extracter.epub included on release page. Then, opened the document and Extractor.epub, and i typed full windows path of my vbk file that recently opened to 'file name' area. 

After I pressed 'extract', as seen on image, Processing and Validating EPUB text always stays and it seems nothing happens.
[ss](http://imgur.com/a/9Ovh1)

**Comment by GMMan** [comment]
You need a version of Bookshelf prior to 6.7.0 (16).

**Comment by Sussid** [comment]
Hi, I have the same issue with it. Using Vitalsource Bookshelf 6.6 on mac.

**Comment by Sussid** [comment]
Is there a way to check or identify the step it is stuck at? Somehow find out the root cause?

**Comment by GMMan** [comment]
Mac is not supported.

**Comment by Sussid** [comment]
Hi,

You happen to have a link to Vitalsource bookshelf 6.7 for Windows?
apparently it's super hard to find one.

Br

**Comment by eckucukoglu** [comment]
[Bookshelf 6.6.3 (Windows) ](https://support.vitalsource.com/hc/en-us/articles/205067177-Bookshelf-6-6-3-Windows-Release-Notes)

**Comment by eckucukoglu** [comment]
After install version 6.2 (24), my books are not shown on application. If i try to open formerly downloaded books, it yields "You do not have a license for this book. This title may be available for purchase online."

**Comment by Sussid** [comment]
Yeah, that link redirects to the latest edition of the VitalSource
Bookshelf software.

Br

**Comment by eckucukoglu** [comment]
So, what can I do, any suggestion?

**Comment by AVKazak** [comment]
Greetings!
What is the VitalSource Bookshelf application for Windows compatible with the extractor? Can you share a download link to it please?
Thank you very much.

**Comment by GMMan** [comment]
The old version can no longer obtain a normal license file, so no point trying it.

**Comment by AVKazak** [comment]
OK. Any workaround for now?

**Comment by GMMan** [comment]
Not for this particular method, but someone else probably published a satisfactory method.

**Comment by AVKazak** [comment]
Can you suggest some starting point to start searching please?

**Comment by AVKazak** [comment]
Can you suggest some starting point to start searching please?
