### ISSUE TITLE
Stuck on "validating EPUB"

### ISSUE THREAD

**Issue by SXRWahrheit** [GMMan/Extractor.epub#16]
Hi! Thanks for writing this. I've tried to run it on a book, and it appears to be stuck at the first step. It wouldn't take the filename alone at first, so I input the entire path instead, and that at least got me to this step.

Is there a debug option so I can see where it's getting stuck, or if it's just taking a long time to process? I see some debug folder on the repository, but I'm not sophisticated enough to know how to build and/or try it.

Thanks again for your time and effort!

**Comment by SXRWahrheit** [comment]
I looked at prior issues and saw that this no longer works on version above 6.6, but I was only able to find an installer for 6.2, on which I'm unable to open my book. If you could update this to work with the latest version, that would be great.

**Comment by minoseah629** [comment]
having the exact same issue

**Comment by GMMan** [comment]
Unfortunately the vulnerability was patched, which is why there isn't an update for newer versions.

**Comment by SXRWahrheit** [comment]
Okay, but what about using the older versions? That seems to be broken also.

**Comment by GMMan** [comment]
Do you still have your regular library instead of the "nuked" version that asks you to update?

**Comment by SXRWahrheit** [comment]
I have the VBK file, but opening it in an old version says I don't own the book.

**Comment by GMMan** [comment]
You have to be able to open the book for this to work.
