### ISSUE TITLE
EPUB book not found

### ISSUE THREAD

**Issue by derganove** [GMMan/Extractor.epub#2]
Found the file in Public Shared, but the extractor still isn't finding it or finding it valid.

"Did not find valid EPUB with that name. Please check that you've typed the name right and have opened the book at least once this session."

I've opened it at least once, can find the physical file myself, and still no dice. I'm going to attempt to put in the entire location...see what happens.

**Comment by derganove** [comment]
That seemed to get me onto the next stage. I'll leave it running.

**Comment by derganove** [comment]
Still unable. Verify stuck.

---

## System Information

```
  Time of this report: 8/11/2015, 22:11:20
         Machine name: DERGANOVE-PC
     Operating System: Windows 10 Pro 64-bit (10.0, Build 10240) (10240.th1.150729-1800)
             Language: English (Regional Setting: English)
  System Manufacturer: ASUS
         System Model: All Series
                 BIOS: Default System BIOS
            Processor: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 CPUs), ~4.0GHz
               Memory: 16384MB RAM
  Available OS Memory: 16260MB RAM
            Page File: 5686MB used, 26956MB available
          Windows Dir: C:\WINDOWS
      DirectX Version: 12
  DX Setup Parameters: Not found
     User DPI Setting: Using System DPI
   System DPI Setting: 144 DPI (150 percent)
      DWM DPI Scaling: UnKnown
             Miracast: Available, with HDCP
```

Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.10240.16384 64bit Unicode

**Comment by jenniferbaker** [comment]
You have to put entire location/name into the filename blank.
Example: 
C:\Users\Public\Documents\Shared Books\VitalSource Bookshelf\VitalBook Library\thisisatest.vbk

**Comment by derganove** [comment]
(See additional comments I've added).

Now it won't go past validating. I've done administrator mode as well.

Posted sysinfo if that helps

**Comment by GMMan** [comment]
You should only input the file name with extension, and not the full path. Using the example given by @jenniferbaker, it would be thisisatest.vbk. However, you want to verify first that the book is actually EPUB and not one of the other formats. You can do this by hovering over the book in your Bookshelf library and reading the popup that appears.

BTW, I do not have access to a Windows 10 installation, and hence do not know if there are compatibility problems there.

**Comment by derganove** [comment]
Ok, so it being a 
"Format: vitalbook" This extractor will not work then?

**Comment by GMMan** [comment]
Indeed. I don't have a simple way of extracting DashML books at this time.
