### ISSUE TITLE
Did not find valid EPUB with that name

### ISSUE THREAD

**Issue by jesterov** [GMMan/Extractor.epub#3]
Hello,

Thank you very much for putting this tool together. Some of the books in my library return the error message: "Did not find valid EPUB with that name. Please check that you've typed the name right and have opened the book at least once this session."

I'm not sure why the process works for some books but not for others. Is there more than one way to do this right?

**Comment by jesterov** [comment]
The format of the book I am unable to extract is "pdfbook." The format of the books that work is "epubbook"

**Comment by GMMan** [comment]
That is the designed behavior. The method used to extract EPUB format books do not apply for PDF format books.

**Comment by jesterov** [comment]
Understood. Is there a tool for 'pdfbooks' ?

**Comment by GMMan** [comment]
You can try the PxcView shim that's on my other repo.
