### ISSUE TITLE
VitalSource error message

### ISSUE THREAD

**Issue by dracunculus** [GMMan/Extractor.epub#5]
When I open extractor.epub i get the message, "You do not have a license for this book.  This title may be available for purchase online."

I'm running VitalSOurce Bookshelf 5.6 on Mac OS 10.9.5.

Any advice?

Thanks

**Comment by GMMan** [comment]
EPUBs can only be sideloaded on VitalSource Bookshelf 6.2 or greater, as mentioned on VitalSource's help centre [here](https://support.vitalsource.com/hc/en-us/articles/203256896-Side-load-EPUB-files-to-Bookshelf-for-Mac-PC).
