### ISSUE TITLE
Processing never ends

### ISSUE THREAD

**Issue by lextorre** [GMMan/Extractor.epub#7]
Hello!

When processing my vbk file, Extractor freezes and shows the following message: "Transferring Misc/MyriadPro-SemiboldIt.woff"

Any idea?

Thanks and congratulations for your great effort!

**Comment by GMMan** [comment]
The ZIP file generated may be too big for the embedded browser engine to handle, so you might want to try the with-backend version.

**Comment by lextorre** [comment]
Sorry, but I didn´t understand what you mean by backend version. Please, could you be more specific?

Thanks.

**Comment by GMMan** [comment]
https://github.com/GMMan/Extractor.epub/releases/tag/v1.0.2

**Comment by lextorre** [comment]
Sorry again. I must be too stupid. Now, I don´t know how to use this new version. I see there is 2 files/; extractor.epub and ExtractorEpubBackend.exe. I run the last one and a black screen opened, but now I really don´t know what to do...

**Comment by lextorre** [comment]
Never mind,GMMan. I got it!! Let me tell you: you are a genious!! Thank you so much for yourjob and patience and sorry for my english!
