### ISSUE TITLE
Cannot extract

### ISSUE THREAD

**Issue by ghost** [GMMan/Extractor.epub#8]
I get an error when entering my filename and clicking "Extract." 

"Failed to parse package file"

**Comment by GMMan** [comment]
If you're trying to use it on any version of Bookshelf at or beyond version 6.7.0 (16), it's not going to work.

**Comment by ghost** [comment]
Do you know where I can get a legacy version of Bookshelf?

**Comment by GMMan** [comment]
Search around. There are various places you can look for archived software and web pages.
