### ISSUE TITLE
Did not find valid EPUB with that name

### ISSUE THREAD

**Issue by LVNGV** [GMMan/Extractor.epub#9]
I followed the instructions and did the following:

I made sure that my .vbk file is in fact a epubbook by hovering over it in Bookshelf (Format: epubbook).
I got the filename with same method (VBID: 97819)

I loaded Extractor.epub into folder C:\Users\Public\Documents\Shared Books\VitalSource Bookshelf\VitalBook Library

I opened my .vbk file and opened the Extractor.epub during the same season.

I entered "97819.vbk" into Extract field and received following error: "Did not find valid EPUB with that name. Please check that you've typed the name right and have opened the book at least once this session." 

Am I missing something or is it a genuine issue?

**Comment by GMMan** [comment]
If you're trying to use it on any version of Bookshelf at or beyond version 6.7.0 (16), it's not going to work.

**Comment by LVNGV** [comment]
You're absolutely correct - it worked perfectly on 6.2 version.

Thanks!
